setwd("~/ExData_Plotting_Project2")
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
library(dplyr)
nei <- tbl_df(NEI)
scc <- tbl_df(SCC)
rm(NEI)
rm(SCC)
#nei$year <- as.factor(nei$year)
totalPM25 <- group_by(nei, year)
totalPM25 <- summarise(totalPM25, emissions = sum(Emissions))
attach(nei)
attach(scc)
attach(totalPM25)
